Write a stored procedure to insert a new order for a given customer, taking customer_id, order_date, and total_amount as input.

Create Proc NEO  ( 
@OID int,
@CIT int,
@date date,
@TA decimal(6,2)) as 

Begin 
insert into Orders (order_id,customer_id,order_date,total_amount) values (@OID,@CIT,@date,@TA)
end

Exec NEO 18,5,'2027-07-11',652.46

Write a stored procedure to return all orders (with order_date and total_amount) for a given customer_id.

Create Proc RAO (
@CID int)
as
Begin
Select customer_id,order_id,order_date,sum(total_amount) TA from Orders 
where customer_id=@CID
Group by customer_id,order_id,order_date
end

Exec RAO 2


Write a stored procedure to update the price of a product for a given product_id and new price.

Create Proc Update_Proprice (
@PID Int,
@NP Decimal(5,2)
)
as
Begin
Update Products
set unit_price=@NP where product_id=@PID
end

EXEC Update_Proprice 110, 120.1

Write a stored procedure to return the total sales (sum of order total amounts) generated by customers working with a given salesperson_id.



Create Proc RTS (
@SID Int)
as
Begin
Select A.salesperson_id,B.customer_id,sum(B.total_amount) TS from CustomerSalesperson A join Orders B on A.customer_id=B.customer_id
where A.salesperson_id = @SID
Group by A.salesperson_id,B.customer_id
End

Exec RTS 501
